---
name: check matrix

on:
  workflow_dispatch:
    inputs:
      parallels:
        description: 'Number of parallels'
        required: false
        default: 4
        type: number

jobs:
  matrix-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_n: [a,b,c,d,e,f,g,h,i,j]
      fail-fast: false
      max-parallel: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: 'the-markup/blacklight-query'
          path: blacklight-query
      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'
      - name: node
        working-directory: ./blacklight-query
        run: npm install
      - name: run thread abc ${{ matrix.node_n }}
        env:
          NODE_N: ${{ matrix.node_n }}
        working-directory: ./blacklight-query
        run: |
          echo "Running parallel node ${{ matrix.node_n }}"
          split -l$((`wc -l <../data/a.in`/10)) ../data/a.in
          if [ ! -f "xa${NODE_N}" ]
          then
             echo "ignored"
          else
            cat xa${NODE_N}
            node --version
            ./blacklight-query < xa${NODE_N}
          fi
          rm -f xa*
      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
          name: blacklight-report-${{ matrix.node_n }}
          path: blacklight-query/outputs/**
          if-no-files-found: warn
          retention-days: 1
  merge-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: matrix-checks
    if: success() || failure()
    steps:
      - uses: actions/checkout@v5
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports
      - name: generate report
        run: |
          ./summary.sh ${GITHUB_RUN_ID}
          ls -lR
      - name: commit to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub actions run ${GITHUB_RUN_ID}"
          file_pattern: "data/*.md"
      # - name: shell
      #   run: |
      #     mkdir reports
      #     ls -lR
      #     for i in downloaded/*
      #     do
      #       echo $i
      #       mv $i/* reports
      #     done
      #     ls -l reports
      - name: upload merged
        uses: actions/upload-artifact@v4
        with:
          name: merged-reports
          path: |
            reports/**
            data/a.in
          if-no-files-found: warn
          retention-days: 1
      - name: delete matrix artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            blacklight-report-*
