---
name: test var
on:
  workflow_dispatch:

jobs:
  set_var:
    runs-on: ubuntu-latest
    outputs:
      TODAY: ${{ steps.set_vars.outputs.TODAY }}
      EMAILS: ${{ steps.set_vars.outputs.EMAILS }}
    steps:
      - name: set vars
        id: set_vars
        run: |
          echo "TODAY=$(date +'%y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "EMAILS=$(cat test.email  | tr -s '\n' ',' | sed -e 's/,$//g')" >> $GITHUB_OUTPUT"

  get_var:
    runs-on: ubuntu-latest
    needs: set_var
    steps:
      - name: display
        env:
          VAR_TODAY: ${{ needs.set_var.outputs.TODAY }}
          VAR_EMAILS: ${{ needs.set_var.outputs.EMAILS }}
          VAR_BRANCH: ${{ github.github_ref_name }}
        run: |
          echo "${VAR_TODAY}"
          echo "${VAR_EMAILS}"
          echo "${VAR_BRANCH}"